version: '3.1'

services:
  backend-service:
    image: 'demo-app'
    container_name: 'demo-backend-container'
    depends_on:
      - database-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-service:5432/demo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - "4444:8080"

  database-service:
    image: 'postgres'
    container_name: 'demo-database-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    ports:
      - "2345:5432"
